# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/s3305023/DMA/DMA.srcs/sources_1/bd/Main/ip/Main_rst_ps8_0_96M_0/Main_rst_ps8_0_96M_0.xci
# IP: The module: 'Main_rst_ps8_0_96M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/s3305023/DMA/DMA.gen/sources_1/bd/Main/ip/Main_rst_ps8_0_96M_0/Main_rst_ps8_0_96M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/s3305023/DMA/DMA.gen/sources_1/bd/Main/ip/Main_rst_ps8_0_96M_0/Main_rst_ps8_0_96M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/s3305023/DMA/DMA.gen/sources_1/bd/Main/ip/Main_rst_ps8_0_96M_0/Main_rst_ps8_0_96M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/s3305023/DMA/DMA.srcs/sources_1/bd/Main/ip/Main_rst_ps8_0_96M_0/Main_rst_ps8_0_96M_0.xci
# IP: The module: 'Main_rst_ps8_0_96M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/s3305023/DMA/DMA.gen/sources_1/bd/Main/ip/Main_rst_ps8_0_96M_0/Main_rst_ps8_0_96M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/s3305023/DMA/DMA.gen/sources_1/bd/Main/ip/Main_rst_ps8_0_96M_0/Main_rst_ps8_0_96M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/s3305023/DMA/DMA.gen/sources_1/bd/Main/ip/Main_rst_ps8_0_96M_0/Main_rst_ps8_0_96M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
