# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Main/Main.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main || ORIG_REF_NAME==Main} -quiet] -quiet

# IP: bd/Main/ip/Main_zynq_ultra_ps_e_0_0/Main_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==Main_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/Main/ip/Main_xbar_0/Main_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_xbar_0 || ORIG_REF_NAME==Main_xbar_0} -quiet] -quiet

# IP: bd/Main/ip/Main_axi_interconnect_0_0/Main_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_axi_interconnect_0_0 || ORIG_REF_NAME==Main_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/Main/ip/Main_rst_ps8_0_96M_0/Main_rst_ps8_0_96M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_rst_ps8_0_96M_0 || ORIG_REF_NAME==Main_rst_ps8_0_96M_0} -quiet] -quiet

# IP: bd/Main/ip/Main_axi_dma_0_0/Main_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_axi_dma_0_0 || ORIG_REF_NAME==Main_axi_dma_0_0} -quiet] -quiet

# IP: bd/Main/ip/Main_smartconnect_0_1/Main_smartconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_smartconnect_0_1 || ORIG_REF_NAME==Main_smartconnect_0_1} -quiet] -quiet

# IP: bd/Main/ip/Main_convoluter_0_1/Main_convoluter_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_convoluter_0_1 || ORIG_REF_NAME==Main_convoluter_0_1} -quiet] -quiet

# IP: bd/Main/ip/Main_auto_ds_0/Main_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_auto_ds_0 || ORIG_REF_NAME==Main_auto_ds_0} -quiet] -quiet

# IP: bd/Main/ip/Main_auto_pc_0/Main_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_auto_pc_0 || ORIG_REF_NAME==Main_auto_pc_0} -quiet] -quiet

# IP: bd/Main/ip/Main_auto_ds_1/Main_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_auto_ds_1 || ORIG_REF_NAME==Main_auto_ds_1} -quiet] -quiet

# IP: bd/Main/ip/Main_auto_pc_1/Main_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_auto_pc_1 || ORIG_REF_NAME==Main_auto_pc_1} -quiet] -quiet

# XDC: /home/s3310914/Documents/eca1/DMA/DMA.gen/sources_1/bd/Main/Main_ooc.xdc
