# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/s3310914/Documents/eca1/DMA/DMA.srcs/sources_1/bd/Main/ip/Main_axi_dma_0_0/Main_axi_dma_0_0.xci
# IP: The module: 'Main_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/s3310914/Documents/eca1/DMA/DMA.gen/sources_1/bd/Main/ip/Main_axi_dma_0_0/Main_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/s3310914/Documents/eca1/DMA/DMA.gen/sources_1/bd/Main/ip/Main_axi_dma_0_0/Main_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/s3310914/Documents/eca1/DMA/DMA.gen/sources_1/bd/Main/ip/Main_axi_dma_0_0/Main_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/s3310914/Documents/eca1/DMA/DMA.srcs/sources_1/bd/Main/ip/Main_axi_dma_0_0/Main_axi_dma_0_0.xci
# IP: The module: 'Main_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/s3310914/Documents/eca1/DMA/DMA.gen/sources_1/bd/Main/ip/Main_axi_dma_0_0/Main_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/s3310914/Documents/eca1/DMA/DMA.gen/sources_1/bd/Main/ip/Main_axi_dma_0_0/Main_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/s3310914/Documents/eca1/DMA/DMA.gen/sources_1/bd/Main/ip/Main_axi_dma_0_0/Main_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
